### ISSUE TITLE
Column Model Issue

### ISSUE THREAD

**Issue by smartinov** [smartinov/fennec#13]
- instead of using is_primary_key, is_nullable, is_herp, is_derp use flags which can be defined and can be true/false. The problem being that we have insconsistent naming (dictionary) and the possibility of extending the data-model with custom "flags" like is GlobalPropertyMatchingID ...

**Comment by smartinov** [comment]
We need to have a set of pre-defined "flags" which we will use for the purposes of SQL generators.

**Comment by darkocolak** [comment]
Elaborate please. 
Because column can be nullable/unique/auto-increment or combination of those.
It cannot be covered with a single flag.
